<?php

/**
 *  VISUALSMODEL.PHP
 *
 *  @author Jonathan Lamb
 */
class VisualsModel {

  // GET STUDENT PERFORMANCE, SINGLE QUESTION

  // GET STUDENT PERFORMANCE, SINGLE TEST

  // GET STUDENT PERFORMANCE, ALL TESTS

  // GET CLASS PERFORMANCE, SINGLE QUESTION

  // GET CLASS PERFORMANCE, SINGLE TEST

  // GET CLASS PERFORMANCE, ALL TESTS

  // GET FEEDBACK, SINGLE QUESTION

  // GET FEEDBACK, SINGLE TEST

  // GET FEEDBACK, ALL TESTS

}
